#pragma once

#define RADAR_ALGORITHM_VERSION_MAJOR 0
#define RADAR_ALGORITHM_VERSION_MINOR 3
#define RADAR_ALGORITHM_VERSION_PATCH 0
#define RADAR_ALGORITHM_VERSION_TWEAK 

#define RADAR_ALGORITHM_VERSION "0.3.0"
#define CMAKE_CONFIGURE_TIME "2025-04-26 20:13:37"
#define RADAR_ALGORITHM_DESCRIPTION "适用于LFMCW雷达的数据处理算法库，最终希望提供一个可移植的C语言库，输入2D-FFT后的雷达中频信号，输出目标跟踪结果"

#define GIT_HASH "fb0f011"
#define GIT_COMMIT_TIME "Sat Apr 26 16:56:02 2025 +0800"
