set(HOST off)
set(CMSISCORE ${PROJECT_SOURCE_DIR}/ThirdParty/CMSIS-Core)
add_subdirectory(${PROJECT_SOURCE_DIR}/ThirdParty/CMSIS-DSP/Source)
add_subdirectory(${PROJECT_SOURCE_DIR}/ThirdParty/STC-4.2)
add_subdirectory(${PROJECT_SOURCE_DIR}/ThirdParty/eigen-3.4.0)
add_subdirectory(${PROJECT_SOURCE_DIR}/Source)
